---
- hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    replicas: 4

  tasks:
    - name: Scale the hello-go deployment with k8s_scale.
      k8s_scale:
        api_version: v1
        kind: Deployment
        name: hello-go
        namespace: default
        replicas: "{{ replicas }}"
        wait: false
