---
- hosts: localhost
  gather_facts: false

  vars_files:
    - vars/main.yml

  tasks:
    - name: Delete CloudFormation stacks.
      cloudformation:
        stack_name: "{{ item }}"
        state: absent
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
      with_items:
        - eks-example-nodegroup
        - eks-example-cluster
        - eks-example-vpc
