---
driver:
  name: delegated
  options:
    managed: true
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker
lint: |
  set -e
  yamllint .
  # ansible-lint
platforms:
  - name: instance-kind
provisioner:
  name: ansible
  log: true
  lint: {}
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  env:
    KUBECONFIG: ~/.kube/config-molecule-test
    K8S_AUTH_KUBECONFIG: ~/.kube/config-molecule-test
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: 'true'
  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
scenario:
  name: default
